apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello
  namespace: argocd              # les Applications vivent dans le namespace d'ArgoCD
spec:
  project: default
  source:
    repoURL: https://github.com/jak13th/gitops-demo.git
    targetRevision: main         # branche, tag ou commit à suivre
    path: apps/hello             # dossier contenant les manifests
  destination:
    server: https://kubernetes.default.svc   # = le cluster local (in-cluster)
    namespace: hello
  syncPolicy:
    automated: true              # ArgoCD synchronise automatiquement les changements
      prune: true                # ArgoCD supprime les ressources qui ne sont plus définies dans Git
      selfHeal: true              # ArgoCD restaure automatiquement l'état désiré si des dérives sont détectées
    syncOptions:
      - CreateNamespace=true     # ArgoCD crée le namespace s'il n'existe pas